server {
    listen 80;
    server_name localhost;

    root /var/www/cafesabrosos;  # Asegúrate de que esta ruta sea correcta
    index index.php index.html index.htm;

    # Bloquear archivos delicados como .env, .sql, node_modules, entre otros
    location ~* \.(env|sql|ini|log|conf|sh|git|svn|backup|node_modules|composer\.json|composer\.lock) {
        deny all;
    }

    location ~ /\. {
        deny all;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;  # Verifica que 'php-fpm' sea el nombre del contenedor adecuado
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /ws {
        proxy_pass http://cafesabrosos-php-fpm-1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Configuración para evitar timeouts en WebSocket
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    error_page 404 /public/error/404.html;
    error_page 403 /public/error/403.html;
}
